### ISSUE TITLE
updating texelFetchBuffer to texelFetch

### ISSUE THREAD

**Issue by brvoigt** [raganmd/learningGLSL#1]
texelFetchBuffer is older some compilers are now failing on it. Recommend changing all texelFetchBuffer with newer texelFetch for better compatibility.

**Comment by raganmd** [comment]
@brvoigt can you give me a little breadcurmb to help track down the places where I've used this?

**Comment by brvoigt** [comment]
Ah! I was originally finding a few in the raymarching examples, but I forgot exactly which ones. So I copied all the .tox I could find here in learningGLSL into one .toe file and used the Tools > Search component in palette. It spit out all these occurrences of texelFetchBuffer. I didn't know I could do that with that search tool, very handy!

![searchresults](https://user-images.githubusercontent.com/8110813/36692189-6a245c7e-1b05-11e8-9296-1dfc64a07851.png)
[texelFetchBuffer.txt](https://github.com/raganmd/learningGLSL/files/1760106/texelFetchBuffer.txt)

**Comment by raganmd** [comment]
moved to texelFetch instead of texelFetchBuffer in commit bb4e6e4

modified toxes include:

        modified:   toxFiles/deferred_lighting/base_deferred_lighting_example.tox
        modified:   toxFiles/deferred_lighting/base_deferred_practice_conelights.tox
        modified:   toxFiles/deferred_lighting/base_deferred_practice_pointlights_instancecolor.tox
        modified:   toxFiles/ray-marching/base_rayMarching_blobs.tox
        modified:   toxFiles/ray-marching/base_rayMarching_bucketsOfLights.tox
        modified:   toxFiles/ray-marching/base_rayMarching_generalFrame.tox
        modified:   toxFiles/ray-marching/base_rayMarching_generalFrame_vorNoise.tox

@brvoigt let me know if I missed one :)
